#### Creating the simple ML model 

***Importing the Libraries***

In [27]:
import joblib
import numpy as np
import pandas as pd 
import matplotlib.pylab as plt 
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import GridSearchCV, train_test_split


***Data prepration***

In [5]:
datasets = load_iris()
X = datasets.data
y = datasets.target


In [6]:
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [22]:
## splitting the datas into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
params = {
    "n_estimators": 100,
    "criterion": "entropy",
    "max_depth": 10,
    "min_samples_split": 2,
    "min_samples_leaf": 1
}

## initalize the model
classifier = RandomForestClassifier(**params)
classifier.fit(X_train, y_train)

## predict the model 
y_pred = classifier.predict(X_test)
print(y_pred)
print(y_test)

[1 2 2 1 2 0 0 1 1 2 1 2 0 0 0 0 0 1 1 1 2 2 1 2 2 1 2 1 2 2]
[1 2 2 1 2 0 0 1 2 2 1 2 0 0 0 0 0 1 1 1 2 2 1 2 2 1 2 1 2 2]


In [28]:
## printitng accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"best accuracy :", accuracy)
joblib.dump(classifier, "model.pkl")

best accuracy : 0.9666666666666667


['model.pkl']